config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :areas
  resources :doctors
  resources :treatments
  resources :patients
  resources :people
  root 'people#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  # validates_presence_of :patient_id, :doctor_id, :duration, :medicament, :prescription
  validate :rules

  belongs_to  :doctors, optional: true
  belongs_to  :patients, optional: true

  def rules
      patient = Patient.find_by_id(patient_id)
      doctor =  Doctor.find_by_id(doctor_id)

      if patient.insuranceplan == "PREMIUM" && doctor.speciality == "Radiology"
        errors.add(patient.firstname, "tiene plan PREMIUM y no se le puede asignar un Radilogo")
      end

      if patient.insuranceplan == "BASIC" && (doctor.speciality != "General Medicine" && doctor.speciality != "Obstetrics" && doctor.speciality != "Pediatrics")
        error = "tiene plan BASIC y su cobertura no cubre la especialidad del Doctor " + doctor.firstname
        errors.add(patient.firstname, error)
      end
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_treatment, only: [:show, :edit, :update, :destroy]

  # GET /treatments
  # GET /treatments.json
  def index
    @treatments = Treatment.all
  end

  # GET /treatments/1
  # GET /treatments/1.json
  def show
  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
  end

  # GET /treatments/1/edit
  def edit
  end

  # POST /treatments
  # POST /treatments.json
  def create
    @treatment = Treatment.new(treatment_params)

    respond_to do |format|
      if @treatment.save
        format.html { redirect_to @treatment, notice: 'Treatment was successfully created.' }
        format.json { render :show, status: :created, location: @treatment }
      else
        format.html { render :new }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treatments/1
  # PATCH/PUT /treatments/1.json
  def update
    respond_to do |format|
      if @treatment.update(treatment_params)
        format.html { redirect_to @treatment, notice: 'Treatment was successfully updated.' }
        format.json { render :show, status: :ok, location: @treatment }
      else
        format.html { render :edit }
        format.json { render json: @treatment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treatments/1
  # DELETE /treatments/1.json
  def destroy
    @treatment.destroy
    respond_to do |format|
      format.html { redirect_to treatments_url, notice: 'Treatment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treatment_params
      params.require(:treatment).permit(:patient_id, :doctor_id, :duration, :medicaments, :prescription)
    end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.haml
= form_for @treatment do |f|
  - if @treatment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@treatment.errors.count, "error")} prohibited this treatment from being saved:"
      %ul
        - @treatment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :patient_id
    = collection_select(:treatment, :patient_id, Patient.all, :id, :firstname,{}, prompt: true)
  .field
    = f.label :doctor_id
    = collection_select(:treatment, :doctor_id, Doctor.all, :id, :firstname,{}, prompt: true )
  .field
    = f.label :duration
    = f.text_field :duration
  .field
    = f.label :medicaments
    = f.text_field :medicaments
  .field
    = f.label :prescription
    = f.text_field :prescription
  .actions
    = f.submit 'Save'

app/views/treatments/edit.html.haml
%h1 Editing treatment

= render 'form'

= link_to 'Show', @treatment
\|
= link_to 'Back', treatments_path

app/views/treatments/index.html.haml
%h1 Treatments

%table(class="table")
  %thead
    %tr
      %th Patient
      %th Doctor
      %th Duration
      %th Medicaments
      %th Prescription
      %th
      %th
      %th

  %tbody
    - @treatments.each do |treatment|
      %tr
        - p = Patient.find_by_id(treatment.patient_id)
        - d = Doctor.find_by_id(treatment.doctor_id)
        %td= p.firstname + " - " + p.insuranceplan
        %td= d.firstname + " - " + d.speciality
        %td= treatment.duration
        %td= treatment.medicaments
        %td= treatment.prescription
        %td= link_to 'Show', treatment
        %td= link_to 'Edit', edit_treatment_path(treatment)
        -# %td= link_to 'Destroy', treatment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Treatment', new_treatment_path

app/views/treatments/new.html.haml
%h1 New treatment

= render 'form'

= link_to 'Back', treatments_path

app/views/treatments/show.html.haml
%p#notice= notice

%p
  %b Patient:
  = @treatment.patient_id
%p
  %b Doctor:
  = @treatment.doctor_id
%p
  %b Duration:
  = @treatment.duration
%p
  %b Medicaments:
  = @treatment.medicaments
%p
  %b Prescription:
  = @treatment.prescription

= link_to 'Edit', edit_treatment_path(@treatment)
\|
= link_to 'Back', treatments_path