config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :areas
  resources :doctors
  resources :treatments
  resources :patients
  resources :people
  root 'people#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  validate :rules


      def rules
        if fecha.year < 2017 || (fecha.year == 2017 && fecha.month < 11) || (fecha.year == 2017 && fecha.month == 11 && fecha.day < 22)
          e = " no se puede atrasar la fecha de la creacion del sistema (22/11/2017)"
          errors.add(:fecha, e)
        else
          d = Doctor.all
          yearDif = fecha.year - 2017
          monthDif =  fecha.month - 11
          dayDif = fecha.day - 22

          totalDays = (yearDif * 365) + (monthDif * 31) + dayDif

          totalYears = totalDays / 365
          totalYears = totalYears.floor

          print("La diferencia de años es: " + totalYears.to_s)



          for i in 0..(d.size-1)
            d[i].yearsexperience = d[i].yearsexperience + totalYears
            for j in 0..totalYears
              d[i].salary = d[i].salary + (d[i].salary * 0.10)
            end
            d[i].save
          end

        end
      end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @calendars = Calendar.all
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:fecha)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.haml
= form_for @calendar do |f|
  - if @calendar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@calendar.errors.count, "error")} prohibited this calendar from being saved:"
      %ul
        - @calendar.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :fecha
    = f.date_select :fecha
  .actions
    = f.submit 'Save'

app/views/calendars/edit.html.haml
%h1 Editing calendar

= render 'form'

= link_to 'Show', @calendar
\|
= link_to 'Back', calendars_path

app/views/calendars/index.html.haml
%h1 Listing calendars

%table(class="table")
  %thead
    %tr
      %th Fecha
      %th
      %th
      %th

  %tbody
    - @calendars.each do |calendar|
      %tr
        %td= calendar.fecha
        %td= link_to 'Show', calendar
        %td= link_to 'Edit', edit_calendar_path(calendar)
        -# %td= link_to 'Destroy', calendar, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Calendar', new_calendar_path

app/views/calendars/new.html.haml
%h1 New calendar

= render 'form'

= link_to 'Back', calendars_path

app/views/calendars/show.html.haml
%p#notice= notice

%p
  %b Fecha:
  = @calendar.fecha

= link_to 'Edit', edit_calendar_path(@calendar)
\|
= link_to 'Back', calendars_path