config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :areas
  resources :doctors
  resources :treatments
  resources :patients
  resources :people
  root 'people#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord

  validate :rules
  belongs_to  :doctors, optional: true

  def rules
    doctor = Doctor.find_by_id(leader)

    arealeaded = Area.find_by_leader(leader)


    # Si no hay doctor
    if doctor == nil
      errors.add(:leader,"error")
    elsif name != doctor.speciality
      error = "no puede ser asignado a esta area porque su especilidad es " + doctor.speciality.downcase
      errors.add(doctor.firstname, error)
    elsif arealeaded != nil
      errorLeaderExits = "ya es lider de otra area"
      errors.add(doctor.firstname, errorLeaderExits)
    end
  end

  def name_with_location
   "#{name} - #{location}"
  end

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:leader, :name, :location)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.haml
= form_for @area do |f|
  - if @area.errors.any?
    #error_explanation
      %h2= "#{pluralize(@area.errors.count, "error")} prohibited this area from being saved:"
      %ul
        - @area.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :leader
    = collection_select(:area, :leader, Doctor.order("speciality ASC").all, :id, :name_with_speciality,{}, prompt: true )
  .field
    = f.label :name
    = f.select(:name, options_for_select([['Allergology','Allergology'],['Radiology','Radiology'],['Cardiology','Cardiology'],['General Medicine','General Medicine'],['Gerontology','Gerontology'],['Obstetrics','Obstetrics'],['Pediatrics','Pediatrics'],['Traumatology','Traumatology']]))
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit 'Save'

app/views/areas/edit.html.haml
%h1 Editing area

= render 'form'

= link_to 'Show', @area
\|
= link_to 'Back', areas_path

app/views/areas/index.html.haml
%h1 Areas

%table(class="table")
  %thead
    %tr
      %th Leader
      %th Name
      %th Location
      %th
      %th
      %th

  %tbody
    - @areas.each do |area|
      %tr
        - d = Doctor.find_by_id(area.leader)
        %td= d.firstname
        %td= area.name
        %td= area.location
        %td= link_to 'Show', area
        %td= link_to 'Edit', edit_area_path(area)
        -# %td= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Area', new_area_path

app/views/areas/new.html.haml
%h1 New area

= render 'form'

= link_to 'Back', areas_path

app/views/areas/show.html.haml
%p#notice= notice

%p
  %b Leader:
  = @area.leader
%p
  %b Name:
  = @area.name
%p
  %b Location:
  = @area.location

= link_to 'Edit', edit_area_path(@area)
\|
= link_to 'Back', areas_path