config/routes.rb
Rails.application.routes.draw do
  resources :calendars
  resources :areas
  resources :doctors
  resources :treatments
  resources :patients
  resources :people
  root 'people#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  acts_as :person
  validate :rules

  belongs_to  :areas, optional: true
  has_one :areas
  has_many :treatments

  def rules
    #Sacar el area a la que pertenece ese doctor
    doctorOld = Doctor.find_by_id(id)

    #Si el doctor ya existia
    if(doctorOld != nil)
      area = Area.find_by_id(doctorOld.area_id) #Radilogy zona 1
      arealeaded =Area.find_by_leader(id)
      t = true

      if area == nil
        errors.add(:area_id, "error")
      elsif area.name != speciality
        error = "no puede ser asignada como area porque la especialidad seleccionada del doctor es " + speciality.downcase
        errors.add(area.name, error)
      elsif arealeaded == nil
        errorleaded = "no se puede cambiar su area porque no es lider"
        errors.add(area.name, errorleaded)
      elsif arealeaded != nil
        d = Doctor.all
        for i in 0..(d.size-1)
          if d[i].area_id == area.id && d[i].id != area.leader
            area.leader = d[i].id
            t = false
            break
          end
        end

        if t
          e = "no se puede cambiar su porque no hay suplente"
          errors.add(firstname, e)
        end

        area.save
      end

    #El doctor es nuevo
    else
      area = Area.find_by_id(id)
      if area.name != speciality
        error = "no puede ser asignada como area porque la especialidad seleccionada del doctor es " + speciality.downcase
        errors.add(area.name, error)
      end
    end


  end

  def name_with_speciality
   "#{firstname} - #{speciality}"
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:area_id, :firstname, :lastname, :dob, :gender, :speciality, :yearsexperience)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.haml
= form_for @doctor do |f|
  - if @doctor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@doctor.errors.count, "error")} prohibited this doctor from being saved:"
      %ul
        - @doctor.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :area_id
    = collection_select(:doctor, :area_id, Area.order("name ASC").all, :id, :name_with_location,{}, prompt: true)
  .field
    = f.label :firstname
    = f.text_field :firstname
  .field
    = f.label :lastname
    = f.text_field :lastname
  .field
    = f.label :dob
    = f.date_field :dob
  .field
    = f.label :gender
    = f.select(:gender, options_for_select([['M','M'] ,['F','F'],['O','O']]))
  .field
    = f.label :speciality
    = f.select(:speciality, options_for_select([['Allergology','Allergology'],['Radiology','Radiology'],['Cardiology','Cardiology'],['General Medicine','General Medicine'],['Gerontology','Gerontology'],['Obstetrics','Obstetrics'],['Pediatrics','Pediatrics'],['Traumatology','Traumatology']]))
  .field
    = f.label :yearsexperience
    = f.number_field :yearsexperience
  .field
    = f.label :salary
    = f.number_field :salary
  .actions
    = f.submit 'Save'

app/views/doctors/edit.html.haml
%h1 Editing doctor

= render 'form'

= link_to 'Show', @doctor
\|
= link_to 'Back', doctors_path

app/views/doctors/index.html.haml
%h1 Doctors

%table(class = "table")
  %thead
    %tr
      %th Area
      %th Firstname
      %th Lastname
      %th Dob
      %th Gender
      %th Speciality
      %th Yearsexperience
      %th Salary
      %th
      %th
      %th

  %tbody
    - @doctors.each do |doctor|
      %tr
        - a = Area.find_by_id(doctor.area_id)
        - zona = a.name + " - " + a.location
        %td= zona
        %td= doctor.firstname
        %td= doctor.lastname
        %td= doctor.dob
        %td= doctor.gender
        %td= doctor.speciality
        %td= doctor.yearsexperience
        %td= doctor.salary
        %td= link_to 'Show', doctor
        %td= link_to 'Edit', edit_doctor_path(doctor)
%br

= link_to 'New Doctor', new_doctor_path

app/views/doctors/new.html.haml
%h1 New doctor

= render 'form'

= link_to 'Back', doctors_path

app/views/doctors/show.html.haml
%p#notice= notice

%p
  %b Area:
  = @doctor.area_id
%p
  %b Firstname:
  = @doctor.firstname
%p
  %b Lastname:
  = @doctor.lastname
%p
  %b Dob:
  = @doctor.dob
%p
  %b Gender:
  = @doctor.gender
%p
  %b Speciality:
  = @doctor.speciality
%p
  %b Yearsexperience:
  = @doctor.yearsexperience

= link_to 'Edit', edit_doctor_path(@doctor)
\|
= link_to 'Back', doctors_path